GAME_TITLE = "Echoes of Pythonia"
GAME_VERSION = "0.24.7"

STARTING_LEVEL = 0
STARTING_HP = 20
STARTING_ATTRIBUTE_POINTS = 0
ATTRIBUTE_POINTS_PER_LEVEL = 4

BASE_FLEE_CHANCE = 0.50

STARTING_LOCATION_ID = "twilight_plains"
STARTING_CITY_ID = "varenhold"
STARTING_DAY = 1
STARTING_HOUR = 8
EXPEDITION_DURATION_HOURS = 1
REST_DURATION_HOURS = 2
CAMP_REST_HP_PERCENT = 0.25
CAMP_REST_MANA_PERCENT = 0.35
INN_REST_DURATION_HOURS = 6
INN_REST_BASE_COST = 25
INN_REST_LEVEL_COST = 25
DUNGEON_ROOM_DURATION_HOURS = 1
REGION_BOSS_RESPAWN_EXPEDITIONS = 6

STARTING_WEAPON_ID = "starter_sword"
STARTING_ARMOR_ID = "worn_leather_armor"

STRENGTH_ATTACK_PER_POINT = 1
VITALITY_HP_PER_POINT = 5
INTELLIGENCE_MANA_PER_POINT = 5
DEXTERITY_DODGE_PER_POINT = 1.5
ENDURANCE_POINTS_PER_DEFENSE = 2

MAX_UPGRADE_LEVEL = 10
MAX_ELEMENTAL_RESISTANCE = 75

PASSIVE_POINT_EVERY_LEVELS = 2
CLASS_UNLOCK_LEVEL = 5
BASIC_PASSIVE_LEVEL = 5
MAX_PASSIVE_LEVEL = 10
BASE_CRITICAL_CHANCE = 5.0

WEATHER_DURATION_HOURS = 6

SAVE_SCHEMA_VERSION = 15
PREVIOUS_SAVE_SCHEMA_VERSION = 14
OLDER_SAVE_SCHEMA_VERSIONS = (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13)
DEFAULT_SAVE_SLOT = "save_1.json"
SAVE_SLOT_COUNT = 4
APP_DATA_FOLDER = "EchoesOfPythonia"
