class_name RegionalEnemyCatalog
extends RefCounted

const DATA := {
	"venom_spider":
	{
		"display_name": "Jadowity Pająk",
		"max_hp": 14,
		"attack": 5,
		"defense": 1,
		"dodge": 15.0,
		"experience_reward": 30,
		"gold_min": 20,
		"gold_max": 28,
		"special_name": "Jadowite Ukąszenie",
		"special_chance": 0.25,
		"special_attack_bonus": 2,
	},
	"forest_cultist":
	{
		"display_name": "Kultysta Boru",
		"max_hp": 18,
		"attack": 6,
		"defense": 2,
		"dodge": 5.0,
		"experience_reward": 36,
		"gold_min": 28,
		"gold_max": 40,
		"special_name": "Mroczny Pocisk",
		"special_chance": 0.25,
		"special_attack_bonus": 2,
	},
	"rotting_knight":
	{
		"display_name": "Zgniły Rycerz",
		"max_hp": 26,
		"attack": 6,
		"defense": 4,
		"dodge": 0.0,
		"experience_reward": 42,
		"gold_min": 40,
		"gold_max": 55,
	},
	"corrupted_bear":
	{
		"display_name": "Spaczony Niedźwiedź",
		"max_hp": 32,
		"attack": 8,
		"defense": 2,
		"dodge": 0.0,
		"experience_reward": 50,
		"gold_min": 55,
		"gold_max": 70,
		"special_name": "Miażdżący Cios",
		"special_chance": 0.2,
		"special_attack_bonus": 3,
	},
	"gallows_wraith":
	{
		"display_name": "Zjawa Wisielca",
		"grammatical_gender": "feminine",
		"max_hp": 20,
		"attack": 7,
		"defense": 2,
		"dodge": 25.0,
		"experience_reward": 46,
		"gold_min": 45,
		"gold_max": 60,
		"special_damage_type": "frost",
	},
	"black_hart":
	{
		"display_name": "Czarny Jeleń",
		"max_hp": 24,
		"attack": 7,
		"defense": 3,
		"dodge": 10.0,
		"experience_reward": 55,
		"gold_min": 60,
		"gold_max": 80,
		"special_name": "Szarża Poroża",
		"special_chance": 0.3,
		"special_attack_bonus": 2,
		"special_damage_type": "earth",
	},
	"blackwood_executioner":
	{
		"display_name": "Leśny Egzekutor",
		"max_hp": 48,
		"attack": 9,
		"defense": 4,
		"dodge": 5.0,
		"experience_reward": 180,
		"gold_min": 180,
		"gold_max": 260,
		"rank": "miniboss",
		"special_name": "Rytualne Cięcie",
		"special_chance": 0.25,
		"special_attack_bonus": 4,
	},
	"bog_crawler":
	{
		"display_name": "Błotny Pełzacz",
		"max_hp": 34,
		"attack": 9,
		"defense": 3,
		"dodge": 10.0,
		"experience_reward": 58,
		"gold_min": 45,
		"gold_max": 60,
		"special_name": "Błotny Wstrząs",
		"special_chance": 0.2,
		"special_attack_bonus": 2,
		"special_damage_type": "earth",
	},
	"drowned_dead":
	{
		"display_name": "Topielec",
		"max_hp": 42,
		"attack": 10,
		"defense": 4,
		"dodge": 0.0,
		"experience_reward": 70,
		"gold_min": 50,
		"gold_max": 70,
		"special_name": "Uścisk Topielca",
		"special_chance": 0.25,
		"special_attack_bonus": 3,
		"special_damage_type": "water",
	},
	"swamp_witch":
	{
		"display_name": "Bagienna Wiedźma",
		"grammatical_gender": "feminine",
		"max_hp": 32,
		"attack": 11,
		"defense": 2,
		"dodge": 15.0,
		"experience_reward": 76,
		"gold_min": 60,
		"gold_max": 80,
		"special_name": "Klątwa Głuchej Wody",
		"special_chance": 0.3,
		"special_attack_bonus": 4,
		"special_damage_type": "water",
	},
	"bone_crocodile":
	{
		"display_name": "Kościany Krokodyl",
		"max_hp": 52,
		"attack": 13,
		"defense": 4,
		"dodge": 0.0,
		"experience_reward": 90,
		"gold_min": 70,
		"gold_max": 95,
		"special_name": "Zacisk Szczęk",
		"special_chance": 0.2,
		"special_attack_bonus": 4,
	},
	"mist_walker":
	{
		"display_name": "Wędrowiec Mgieł",
		"max_hp": 36,
		"attack": 11,
		"defense": 3,
		"dodge": 30.0,
		"experience_reward": 95,
		"gold_min": 75,
		"gold_max": 100,
		"special_name": "Cięcie z Mgły",
		"special_chance": 0.25,
		"special_attack_bonus": 3,
		"special_damage_type": "wind",
	},
	"sunken_knight":
	{
		"display_name": "Rycerz Zatopionego Zakonu",
		"max_hp": 60,
		"attack": 12,
		"defense": 7,
		"dodge": 0.0,
		"experience_reward": 115,
		"gold_min": 90,
		"gold_max": 120,
		"special_name": "Zardzewiały Zamach",
		"special_chance": 0.2,
		"special_attack_bonus": 4,
	},
	"drowned_mother":
	{
		"display_name": "Matka Głuchej Wody",
		"max_hp": 95,
		"attack": 15,
		"defense": 6,
		"dodge": 10.0,
		"experience_reward": 400,
		"gold_min": 300,
		"gold_max": 450,
		"rank": "miniboss",
		"special_name": "Pieśń Utopionych",
		"special_chance": 0.3,
		"special_attack_bonus": 5,
		"special_damage_type": "water",
	},
	"desert_wanderer":
	{
		"display_name": "Pustynny Wędrowiec",
		"max_hp": 210,
		"attack": 24,
		"defense": 8,
		"dodge": 10.0,
		"experience_reward": 180,
		"gold_min": 85,
		"gold_max": 110,
		"special_name": "Cięcie Pustkowi",
		"special_chance": 0.22,
		"special_attack_bonus": 5,
	},
	"desert_harpy":
	{
		"display_name": "Pustynna Harpia",
		"grammatical_gender": "feminine",
		"max_hp": 190,
		"attack": 22,
		"defense": 5,
		"dodge": 25.0,
		"experience_reward": 190,
		"gold_min": 90,
		"gold_max": 120,
		"special_name": "Pikowanie",
		"special_chance": 0.25,
		"special_attack_bonus": 6,
		"special_damage_type": "wind",
		"extra_attack_chance": 0.12,
	},
	"red_salamander":
	{
		"display_name": "Czerwona Salamandra",
		"grammatical_gender": "feminine",
		"max_hp": 250,
		"attack": 25,
		"defense": 7,
		"dodge": 10.0,
		"experience_reward": 220,
		"gold_min": 100,
		"gold_max": 130,
		"special_name": "Ognisty Oddech",
		"special_chance": 0.28,
		"special_attack_bonus": 7,
		"special_damage_type": "fire",
		"elemental_resistances": {"fire": 40},
	},
	"boneburner":
	{
		"display_name": "Kościopal",
		"max_hp": 330,
		"attack": 29,
		"defense": 9,
		"dodge": 0.0,
		"experience_reward": 260,
		"gold_min": 120,
		"gold_max": 155,
		"special_name": "Rozpalony Zamach",
		"special_chance": 0.24,
		"special_attack_bonus": 8,
		"special_damage_type": "fire",
	},
	"sand_golem":
	{
		"display_name": "Piaskowy Golem",
		"max_hp": 440,
		"attack": 27,
		"defense": 16,
		"dodge": 0.0,
		"experience_reward": 300,
		"gold_min": 135,
		"gold_max": 170,
		"special_name": "Piaskowy Młot",
		"special_chance": 0.22,
		"special_attack_bonus": 8,
		"special_damage_type": "earth",
		"physical_damage_reduction": 2,
		"elemental_resistances": {"earth": 35},
	},
	"hearth_devourer":
	{
		"display_name": "Pożeracz Palenisk",
		"max_hp": 1050,
		"attack": 32,
		"defense": 12,
		"dodge": 5.0,
		"experience_reward": 800,
		"gold_min": 350,
		"gold_max": 500,
		"rank": "miniboss",
		"special_name": "Wybuch Paleniska",
		"special_chance": 0.3,
		"special_attack_bonus": 10,
		"special_damage_type": "fire",
		"elemental_resistances": {"fire": 50},
		"status_resistance": 0.25,
	},
	"frozen_castaway":
	{
		"display_name": "Zamarznięty Rozbitek",
		"max_hp": 390,
		"attack": 37,
		"defense": 13,
		"dodge": 8.0,
		"experience_reward": 310,
		"gold_min": 140,
		"gold_max": 185,
		"special_name": "Zamrożone Ostrze",
		"special_chance": 0.24,
		"special_attack_bonus": 9,
		"special_damage_type": "frost",
		"elemental_resistances": {"frost": 20},
	},
	"ice_bear":
	{
		"display_name": "Lodowy Niedźwiedź",
		"max_hp": 530,
		"attack": 42,
		"defense": 16,
		"dodge": 5.0,
		"experience_reward": 365,
		"gold_min": 160,
		"gold_max": 210,
		"special_name": "Rozszarpanie",
		"special_chance": 0.25,
		"special_attack_bonus": 11,
		"first_attack_bonus": 4,
		"elemental_resistances": {"frost": 35},
	},
	"snow_griffin":
	{
		"display_name": "Śnieżny Gryf",
		"max_hp": 430,
		"attack": 40,
		"defense": 10,
		"dodge": 25.0,
		"experience_reward": 360,
		"gold_min": 155,
		"gold_max": 205,
		"special_name": "Pikowanie znad Klifu",
		"special_chance": 0.25,
		"special_attack_bonus": 11,
		"special_damage_type": "wind",
		"extra_attack_chance": 0.12,
		"elemental_resistances": {"wind": 30},
	},
	"ice_crab":
	{
		"display_name": "Lodowy Krab",
		"max_hp": 610,
		"attack": 36,
		"defense": 23,
		"dodge": 0.0,
		"experience_reward": 390,
		"gold_min": 170,
		"gold_max": 225,
		"special_name": "Lodowe Szczypce",
		"special_chance": 0.22,
		"special_attack_bonus": 10,
		"special_damage_type": "frost",
		"physical_damage_reduction": 3,
		"elemental_resistances": {"frost": 45, "water": 25},
	},
	"black_sea_siren":
	{
		"display_name": "Syrena Czarnego Morza",
		"grammatical_gender": "feminine",
		"max_hp": 660,
		"attack": 45,
		"defense": 16,
		"dodge": 20.0,
		"experience_reward": 470,
		"gold_min": 200,
		"gold_max": 270,
		"special_name": "Pieśń Czarnego Morza",
		"special_chance": 0.3,
		"special_attack_bonus": 13,
		"special_damage_type": "water",
		"elemental_resistances": {"water": 50, "frost": 30},
		"status_resistance": 0.2,
	},
	"ghost_ship_captain":
	{
		"display_name": "Widmo Kapitana Statku",
		"max_hp": 1480,
		"attack": 49,
		"defense": 19,
		"dodge": 18.0,
		"experience_reward": 1150,
		"gold_min": 520,
		"gold_max": 720,
		"rank": "miniboss",
		"special_name": "Salwa Widmowego Okrętu",
		"special_chance": 0.3,
		"special_attack_bonus": 14,
		"special_damage_type": "water",
		"elemental_resistances": {"water": 55, "frost": 35},
		"status_resistance": 0.3,
	},
}
